name: Periodic Scan
on:
  workflow_dispatch:
  schedule:
    - cron: "* * * * *"

jobs:
  build_app:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: 'stable'

      - name: Install dependencies
        working-directory: ostorlab_insecure_flutter_app
        run: flutter pub get

      - name: Build IPA
        working-directory: ostorlab_insecure_flutter_app
        run: flutter build ipa --no-sound-null-safety --no-codesign

      # TODO(Anas): remove this.
      - name: discovery
        run: bash -c 'ls /Users/runner/work/ostorlab_insecure_ios_app/ostorlab_insecure_ios_app/ostorlab_insecure_flutter_app/build/ios/'

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: Ipa-file
          path: build/ios/ipa/*.ipa

  run_scan:
    runs-on: ubuntu-latest
    needs: build_app
    steps:
      - name: Download IPA
        uses: actions/download-artifact@v3
        with:
          name: Ipa-file
      - name: Run Scan
        uses: Ostorlab/ostorlab_actions@v1.1.1
        with:
          scan_profile: full_scan
          asset_type: ios-ipa
          scan_title: Periodic_Insecure_ipa
          target: Runner.ipa
          ostorlab_api_key: ${{ secrets.ostorlab_api_key }}