name: Release IPA
on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: 'stable'

      - name: Install dependencies
        working-directory: ostorlab_insecure_flutter_app
        run: flutter pub get

      - name: Build IPA files
        working-directory: ostorlab_insecure_flutter_app
        run: flutter build ipa --no-sound-null-safety --no-codesign

      - name: Build IPA app
        working-directory: ostorlab_insecure_flutter_app
        run: |
          mkdir ostorlab_insecure_app
          cp -r build/ios/Release-iphoneos/* ostorlab_insecure_app/
          zip ostorlab_insecure_app
          mv ostorlab_insecure_app.zip ostorlab_insecure_app.ipa

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ostorlab_insecure_app.ipa